### ISSUE TITLE
How to compile it for armhf platforms

### ISSUE THREAD

**Issue by Scientist786** [nshiell/blue-log-viewer#1]
Hello,
I compiled the application successfully on my Ubuntu laptop. It even ran smoothly. I cannot run it on my raspberry pi which was my ultimate goal. Can you please identify a way to compile it for armhf platforms?

**Comment by nshiell** [comment]
What distro are you using on your Pi?
You should be able to install the required packages from either your distro's package installer or pip

Please post here what version of Raspberry Pi you have
What OS and version ... and what you tried and when errors you saw

**Comment by nshiell** [comment]
No communication on this issue for over a year, I built it on an ARM platform
